/**
 * RARE 4N - Fonts Library
 * مكتبة الخطوط المتنسقة (30+ خط)
 */

export interface Font {
  id: string;
  name: string;
  nameAr: string;
  family: string;
  weight?: string;
  description: string;
  descriptionAr: string;
}

export const FONTS_LIBRARY: Font[] = [
  {
    id: 'system',
    name: 'System',
    nameAr: 'النظام',
    family: 'System',
    description: 'Default system font',
    descriptionAr: 'خط النظام الافتراضي',
  },
  {
    id: 'sf-pro',
    name: 'SF Pro',
    nameAr: 'إس إف برو',
    family: 'System',
    weight: '400',
    description: 'Apple system font',
    descriptionAr: 'خط نظام أبل',
  },
  {
    id: 'helvetica',
    name: 'Helvetica',
    nameAr: 'هيلفيتيكا',
    family: 'System',
    description: 'Classic Helvetica',
    descriptionAr: 'هيلفيتيكا الكلاسيكي',
  },
  {
    id: 'arial',
    name: 'Arial',
    nameAr: 'آريال',
    family: 'System',
    description: 'Arial font',
    descriptionAr: 'خط آريال',
  },
  {
    id: 'roboto',
    name: 'Roboto',
    nameAr: 'روبوتو',
    family: 'System',
    description: 'Google Roboto',
    descriptionAr: 'روبوتو من جوجل',
  },
  {
    id: 'inter',
    name: 'Inter',
    nameAr: 'إنتر',
    family: 'System',
    description: 'Modern Inter font',
    descriptionAr: 'خط إنتر الحديث',
  },
  {
    id: 'poppins',
    name: 'Poppins',
    nameAr: 'بوبينز',
    family: 'System',
    description: 'Poppins font',
    descriptionAr: 'خط بوبينز',
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    nameAr: 'مونتسيرات',
    family: 'System',
    description: 'Montserrat font',
    descriptionAr: 'خط مونتسيرات',
  },
  {
    id: 'open-sans',
    name: 'Open Sans',
    nameAr: 'أوبن سانس',
    family: 'System',
    description: 'Open Sans font',
    descriptionAr: 'خط أوبن سانس',
  },
  {
    id: 'lato',
    name: 'Lato',
    nameAr: 'لاتو',
    family: 'System',
    description: 'Lato font',
    descriptionAr: 'خط لاتو',
  },
  {
    id: 'raleway',
    name: 'Raleway',
    nameAr: 'رالواي',
    family: 'System',
    description: 'Raleway font',
    descriptionAr: 'خط رالواي',
  },
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    nameAr: 'أوبونتو',
    family: 'System',
    description: 'Ubuntu font',
    descriptionAr: 'خط أوبونتو',
  },
  {
    id: 'source-sans',
    name: 'Source Sans',
    nameAr: 'سورس سانس',
    family: 'System',
    description: 'Source Sans Pro',
    descriptionAr: 'سورس سانس برو',
  },
  {
    id: 'nunito',
    name: 'Nunito',
    nameAr: 'نونيتو',
    family: 'System',
    description: 'Nunito font',
    descriptionAr: 'خط نونيتو',
  },
  {
    id: 'playfair',
    name: 'Playfair',
    nameAr: 'بلايفير',
    family: 'System',
    description: 'Playfair Display',
    descriptionAr: 'بلايفير ديسبلاي',
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    nameAr: 'ميريويذر',
    family: 'System',
    description: 'Merriweather font',
    descriptionAr: 'خط ميريويذر',
  },
  {
    id: 'crimson',
    name: 'Crimson',
    nameAr: 'كريمسون',
    family: 'System',
    description: 'Crimson Text',
    descriptionAr: 'كريمسون تيكست',
  },
  {
    id: 'lora',
    name: 'Lora',
    nameAr: 'لورا',
    family: 'System',
    description: 'Lora font',
    descriptionAr: 'خط لورا',
  },
  {
    id: 'pt-sans',
    name: 'PT Sans',
    nameAr: 'بي تي سانس',
    family: 'System',
    description: 'PT Sans font',
    descriptionAr: 'خط بي تي سانس',
  },
  {
    id: 'dosis',
    name: 'Dosis',
    nameAr: 'دوسيس',
    family: 'System',
    description: 'Dosis font',
    descriptionAr: 'خط دوسيس',
  },
  {
    id: 'oswald',
    name: 'Oswald',
    nameAr: 'أوسوالد',
    family: 'System',
    description: 'Oswald font',
    descriptionAr: 'خط أوسوالد',
  },
  {
    id: 'fjalla',
    name: 'Fjalla One',
    nameAr: 'فجالا',
    family: 'System',
    description: 'Fjalla One font',
    descriptionAr: 'خط فجالا',
  },
  {
    id: 'bebas',
    name: 'Bebas Neue',
    nameAr: 'بيباس',
    family: 'System',
    description: 'Bebas Neue font',
    descriptionAr: 'خط بيباس',
  },
  {
    id: 'anton',
    name: 'Anton',
    nameAr: 'أنطون',
    family: 'System',
    description: 'Anton font',
    descriptionAr: 'خط أنطون',
  },
  {
    id: 'righteous',
    name: 'Righteous',
    nameAr: 'رايتيوس',
    family: 'System',
    description: 'Righteous font',
    descriptionAr: 'خط رايتيوس',
  },
  {
    id: 'comfortaa',
    name: 'Comfortaa',
    nameAr: 'كومفورتا',
    family: 'System',
    description: 'Comfortaa font',
    descriptionAr: 'خط كومفورتا',
  },
  {
    id: 'quicksand',
    name: 'Quicksand',
    nameAr: 'كويكساند',
    family: 'System',
    description: 'Quicksand font',
    descriptionAr: 'خط كويكساند',
  },
  {
    id: 'work-sans',
    name: 'Work Sans',
    nameAr: 'ورك سانس',
    family: 'System',
    description: 'Work Sans font',
    descriptionAr: 'خط ورك سانس',
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    nameAr: 'سبيس جروتسك',
    family: 'System',
    description: 'Space Grotesk font',
    descriptionAr: 'خط سبيس جروتسك',
  },
  {
    id: 'manrope',
    name: 'Manrope',
    nameAr: 'مانروب',
    family: 'System',
    description: 'Manrope font',
    descriptionAr: 'خط مانروب',
  },
  {
    id: 'epilogue',
    name: 'Epilogue',
    nameAr: 'إبيلوغ',
    family: 'System',
    description: 'Epilogue font',
    descriptionAr: 'خط إبيلوغ',
  },
  {
    id: 'sora',
    name: 'Sora',
    nameAr: 'سورا',
    family: 'System',
    description: 'Sora font',
    descriptionAr: 'خط سورا',
  },
];

export const DEFAULT_FONT = FONTS_LIBRARY[0];

export default FONTS_LIBRARY;

 * RARE 4N - Fonts Library
 * مكتبة الخطوط المتنسقة (30+ خط)
 */

export interface Font {
  id: string;
  name: string;
  nameAr: string;
  family: string;
  weight?: string;
  description: string;
  descriptionAr: string;
}

export const FONTS_LIBRARY: Font[] = [
  {
    id: 'system',
    name: 'System',
    nameAr: 'النظام',
    family: 'System',
    description: 'Default system font',
    descriptionAr: 'خط النظام الافتراضي',
  },
  {
    id: 'sf-pro',
    name: 'SF Pro',
    nameAr: 'إس إف برو',
    family: 'System',
    weight: '400',
    description: 'Apple system font',
    descriptionAr: 'خط نظام أبل',
  },
  {
    id: 'helvetica',
    name: 'Helvetica',
    nameAr: 'هيلفيتيكا',
    family: 'System',
    description: 'Classic Helvetica',
    descriptionAr: 'هيلفيتيكا الكلاسيكي',
  },
  {
    id: 'arial',
    name: 'Arial',
    nameAr: 'آريال',
    family: 'System',
    description: 'Arial font',
    descriptionAr: 'خط آريال',
  },
  {
    id: 'roboto',
    name: 'Roboto',
    nameAr: 'روبوتو',
    family: 'System',
    description: 'Google Roboto',
    descriptionAr: 'روبوتو من جوجل',
  },
  {
    id: 'inter',
    name: 'Inter',
    nameAr: 'إنتر',
    family: 'System',
    description: 'Modern Inter font',
    descriptionAr: 'خط إنتر الحديث',
  },
  {
    id: 'poppins',
    name: 'Poppins',
    nameAr: 'بوبينز',
    family: 'System',
    description: 'Poppins font',
    descriptionAr: 'خط بوبينز',
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    nameAr: 'مونتسيرات',
    family: 'System',
    description: 'Montserrat font',
    descriptionAr: 'خط مونتسيرات',
  },
  {
    id: 'open-sans',
    name: 'Open Sans',
    nameAr: 'أوبن سانس',
    family: 'System',
    description: 'Open Sans font',
    descriptionAr: 'خط أوبن سانس',
  },
  {
    id: 'lato',
    name: 'Lato',
    nameAr: 'لاتو',
    family: 'System',
    description: 'Lato font',
    descriptionAr: 'خط لاتو',
  },
  {
    id: 'raleway',
    name: 'Raleway',
    nameAr: 'رالواي',
    family: 'System',
    description: 'Raleway font',
    descriptionAr: 'خط رالواي',
  },
  {
    id: 'ubuntu',
    name: 'Ubuntu',
    nameAr: 'أوبونتو',
    family: 'System',
    description: 'Ubuntu font',
    descriptionAr: 'خط أوبونتو',
  },
  {
    id: 'source-sans',
    name: 'Source Sans',
    nameAr: 'سورس سانس',
    family: 'System',
    description: 'Source Sans Pro',
    descriptionAr: 'سورس سانس برو',
  },
  {
    id: 'nunito',
    name: 'Nunito',
    nameAr: 'نونيتو',
    family: 'System',
    description: 'Nunito font',
    descriptionAr: 'خط نونيتو',
  },
  {
    id: 'playfair',
    name: 'Playfair',
    nameAr: 'بلايفير',
    family: 'System',
    description: 'Playfair Display',
    descriptionAr: 'بلايفير ديسبلاي',
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    nameAr: 'ميريويذر',
    family: 'System',
    description: 'Merriweather font',
    descriptionAr: 'خط ميريويذر',
  },
  {
    id: 'crimson',
    name: 'Crimson',
    nameAr: 'كريمسون',
    family: 'System',
    description: 'Crimson Text',
    descriptionAr: 'كريمسون تيكست',
  },
  {
    id: 'lora',
    name: 'Lora',
    nameAr: 'لورا',
    family: 'System',
    description: 'Lora font',
    descriptionAr: 'خط لورا',
  },
  {
    id: 'pt-sans',
    name: 'PT Sans',
    nameAr: 'بي تي سانس',
    family: 'System',
    description: 'PT Sans font',
    descriptionAr: 'خط بي تي سانس',
  },
  {
    id: 'dosis',
    name: 'Dosis',
    nameAr: 'دوسيس',
    family: 'System',
    description: 'Dosis font',
    descriptionAr: 'خط دوسيس',
  },
  {
    id: 'oswald',
    name: 'Oswald',
    nameAr: 'أوسوالد',
    family: 'System',
    description: 'Oswald font',
    descriptionAr: 'خط أوسوالد',
  },
  {
    id: 'fjalla',
    name: 'Fjalla One',
    nameAr: 'فجالا',
    family: 'System',
    description: 'Fjalla One font',
    descriptionAr: 'خط فجالا',
  },
  {
    id: 'bebas',
    name: 'Bebas Neue',
    nameAr: 'بيباس',
    family: 'System',
    description: 'Bebas Neue font',
    descriptionAr: 'خط بيباس',
  },
  {
    id: 'anton',
    name: 'Anton',
    nameAr: 'أنطون',
    family: 'System',
    description: 'Anton font',
    descriptionAr: 'خط أنطون',
  },
  {
    id: 'righteous',
    name: 'Righteous',
    nameAr: 'رايتيوس',
    family: 'System',
    description: 'Righteous font',
    descriptionAr: 'خط رايتيوس',
  },
  {
    id: 'comfortaa',
    name: 'Comfortaa',
    nameAr: 'كومفورتا',
    family: 'System',
    description: 'Comfortaa font',
    descriptionAr: 'خط كومفورتا',
  },
  {
    id: 'quicksand',
    name: 'Quicksand',
    nameAr: 'كويكساند',
    family: 'System',
    description: 'Quicksand font',
    descriptionAr: 'خط كويكساند',
  },
  {
    id: 'work-sans',
    name: 'Work Sans',
    nameAr: 'ورك سانس',
    family: 'System',
    description: 'Work Sans font',
    descriptionAr: 'خط ورك سانس',
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    nameAr: 'سبيس جروتسك',
    family: 'System',
    description: 'Space Grotesk font',
    descriptionAr: 'خط سبيس جروتسك',
  },
  {
    id: 'manrope',
    name: 'Manrope',
    nameAr: 'مانروب',
    family: 'System',
    description: 'Manrope font',
    descriptionAr: 'خط مانروب',
  },
  {
    id: 'epilogue',
    name: 'Epilogue',
    nameAr: 'إبيلوغ',
    family: 'System',
    description: 'Epilogue font',
    descriptionAr: 'خط إبيلوغ',
  },
  {
    id: 'sora',
    name: 'Sora',
    nameAr: 'سورا',
    family: 'System',
    description: 'Sora font',
    descriptionAr: 'خط سورا',
  },
];

export const DEFAULT_FONT = FONTS_LIBRARY[0];

export default FONTS_LIBRARY;


