/**
 * RARE 4N - Themes Library
 * مكتبة الثيمات للـ Control Room (20+ ثيم)
 */

import { Theme } from '../config/themes';

export interface ThemeOption {
  id: string;
  name: string;
  nameAr: string;
  theme: Theme;
  description: string;
  descriptionAr: string;
  category: 'classic' | 'modern' | 'dark' | 'light' | 'colorful';
}

export const THEMES_LIBRARY: ThemeOption[] = [
  {
    id: 'rare-cyan',
    name: 'RARE Cyan',
    nameAr: 'سيان رير',
    theme: {
      id: 'rare-cyan',
      name: 'RARE Cyan',
      nameAr: 'سيان رير',
      primary: '#00EAFF',
      secondary: '#10A37F',
      accent: '#AF52DE',
      background: ['#000408', '#001820', '#000408'],
      surface: '#0a0e14',
      text: '#ffffff',
      textSecondary: '#888888',
      border: '#1a1f2e',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#00EAFF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Classic RARE identity theme',
    descriptionAr: 'ثيم هوية رير الكلاسيكي',
    category: 'classic',
  },
  {
    id: 'stealth-gold',
    name: 'Stealth Gold',
    nameAr: 'الذهب الخفي',
    theme: {
      id: 'stealth-gold',
      name: 'Stealth Gold',
      nameAr: 'الذهب الخفي',
      primary: '#D4AF37',
      secondary: '#8B6B1E',
      accent: '#FFFFFF',
      background: ['#050505', '#1a1400', '#050505'],
      surface: 'rgba(212, 175, 55, 0.1)',
      text: '#FFFFFF',
      textSecondary: '#C0C0C0',
      border: 'rgba(212, 175, 55, 0.4)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 25,
      iconStyle: 'gradient',
      iconColor: '#D4AF37',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Luxury military stealth theme',
    descriptionAr: 'ثيم فخامة عسكرية خفية',
    category: 'classic',
  },
  {
    id: 'royal-crimson',
    name: 'Royal Crimson',
    nameAr: 'الياقوت الملكي',
    theme: {
      id: 'royal-crimson',
      name: 'Royal Crimson',
      nameAr: 'الياقوت الملكي',
      primary: '#FF3B30',
      secondary: '#800000',
      accent: '#00EAFF',
      background: ['#0a0000', '#250000', '#0a0000'],
      surface: 'rgba(255, 59, 48, 0.1)',
      text: '#ffffff',
      textSecondary: '#ffcccc',
      border: 'rgba(255, 59, 48, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FF3B30',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Royal crimson theme',
    descriptionAr: 'ثيم الياقوت الملكي',
    category: 'classic',
  },
  {
    id: 'deep-nebula',
    name: 'Deep Nebula',
    nameAr: 'سديم الفضاء',
    theme: {
      id: 'deep-nebula',
      name: 'Deep Nebula',
      nameAr: 'سديم الفضاء',
      primary: '#AF52DE',
      secondary: '#5856D6',
      accent: '#14F195',
      background: ['#020005', '#120025', '#020005'],
      surface: 'rgba(175, 82, 222, 0.15)',
      text: '#ffffff',
      textSecondary: '#d6bcf5',
      border: 'rgba(175, 82, 222, 0.4)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 30,
      iconStyle: 'filled',
      iconColor: '#AF52DE',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Deep space nebula theme',
    descriptionAr: 'ثيم سديم الفضاء العميق',
    category: 'dark',
  },
  {
    id: 'icy-platinum',
    name: 'Icy Platinum',
    nameAr: 'البلاتين الجليدي',
    theme: {
      id: 'icy-platinum',
      name: 'Icy Platinum',
      nameAr: 'البلاتين الجليدي',
      primary: '#E5E5EA',
      secondary: '#8E8E93',
      accent: '#00EAFF',
      background: ['#000000', '#1c1c1e', '#000000'],
      surface: 'rgba(229, 229, 234, 0.05)',
      text: '#ffffff',
      textSecondary: '#8E8E93',
      border: 'rgba(229, 229, 234, 0.2)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: false,
      blur: 25,
      iconStyle: 'outline',
      iconColor: '#E5E5EA',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Icy platinum theme',
    descriptionAr: 'ثيم البلاتين الجليدي',
    category: 'light',
  },
  {
    id: 'cyber-emerald',
    name: 'Cyber Emerald',
    nameAr: 'الزمرد السيبراني',
    theme: {
      id: 'cyber-emerald',
      name: 'Cyber Emerald',
      nameAr: 'الزمرد السيبراني',
      primary: '#00FF41',
      secondary: '#008F11',
      accent: '#D4AF37',
      background: ['#000500', '#001a05', '#000500'],
      surface: 'rgba(0, 255, 65, 0.1)',
      text: '#ffffff',
      textSecondary: '#00FF41',
      border: 'rgba(0, 255, 65, 0.5)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 15,
      iconStyle: 'filled',
      iconColor: '#00FF41',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Cyber emerald matrix theme',
    descriptionAr: 'ثيم الزمرد السيبراني',
    category: 'dark',
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    nameAr: 'أعماق المحيط',
    theme: {
      id: 'ocean-deep',
      name: 'Ocean Deep',
      nameAr: 'أعماق المحيط',
      primary: '#00D4FF',
      secondary: '#0066CC',
      accent: '#00FF88',
      background: ['#000510', '#001020', '#000510'],
      surface: 'rgba(0, 212, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#88DDFF',
      border: 'rgba(0, 212, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#00D4FF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Deep ocean theme',
    descriptionAr: 'ثيم أعماق المحيط',
    category: 'dark',
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    nameAr: 'برتقالي الغروب',
    theme: {
      id: 'sunset-orange',
      name: 'Sunset Orange',
      nameAr: 'برتقالي الغروب',
      primary: '#FF6600',
      secondary: '#CC3300',
      accent: '#FFCC00',
      background: ['#0a0500', '#1a0a00', '#0a0500'],
      surface: 'rgba(255, 102, 0, 0.1)',
      text: '#ffffff',
      textSecondary: '#FFCC99',
      border: 'rgba(255, 102, 0, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FF6600',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Sunset orange theme',
    descriptionAr: 'ثيم برتقالي الغروب',
    category: 'colorful',
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    nameAr: 'أخضر الغابة',
    theme: {
      id: 'forest-green',
      name: 'Forest Green',
      nameAr: 'أخضر الغابة',
      primary: '#10A37F',
      secondary: '#006644',
      accent: '#00FF88',
      background: ['#000a05', '#001a0f', '#000a05'],
      surface: 'rgba(16, 163, 127, 0.1)',
      text: '#ffffff',
      textSecondary: '#88FFCC',
      border: 'rgba(16, 163, 127, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#10A37F',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Forest green theme',
    descriptionAr: 'ثيم أخضر الغابة',
    category: 'dark',
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    nameAr: 'أزرق منتصف الليل',
    theme: {
      id: 'midnight-blue',
      name: 'Midnight Blue',
      nameAr: 'أزرق منتصف الليل',
      primary: '#0066FF',
      secondary: '#0033CC',
      accent: '#00CCFF',
      background: ['#000510', '#001020', '#000510'],
      surface: 'rgba(0, 102, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#88CCFF',
      border: 'rgba(0, 102, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#0066FF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Midnight blue theme',
    descriptionAr: 'ثيم أزرق منتصف الليل',
    category: 'dark',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    nameAr: 'الذهب الوردي',
    theme: {
      id: 'rose-gold',
      name: 'Rose Gold',
      nameAr: 'الذهب الوردي',
      primary: '#FFB6C1',
      secondary: '#FF69B4',
      accent: '#FF1493',
      background: ['#0a0505', '#1a0a0a', '#0a0505'],
      surface: 'rgba(255, 182, 193, 0.1)',
      text: '#ffffff',
      textSecondary: '#FFCCDD',
      border: 'rgba(255, 182, 193, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FFB6C1',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Rose gold theme',
    descriptionAr: 'ثيم الذهب الوردي',
    category: 'colorful',
  },
  {
    id: 'silver-mist',
    name: 'Silver Mist',
    nameAr: 'ضباب الفضة',
    theme: {
      id: 'silver-mist',
      name: 'Silver Mist',
      nameAr: 'ضباب الفضة',
      primary: '#C0C0C0',
      secondary: '#808080',
      accent: '#FFFFFF',
      background: ['#0a0a0a', '#1a1a1a', '#0a0a0a'],
      surface: 'rgba(192, 192, 192, 0.1)',
      text: '#ffffff',
      textSecondary: '#C0C0C0',
      border: 'rgba(192, 192, 192, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: false,
      blur: 25,
      iconStyle: 'outline',
      iconColor: '#C0C0C0',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Silver mist theme',
    descriptionAr: 'ثيم ضباب الفضة',
    category: 'light',
  },
  {
    id: 'volcanic-red',
    name: 'Volcanic Red',
    nameAr: 'الأحمر البركاني',
    theme: {
      id: 'volcanic-red',
      name: 'Volcanic Red',
      nameAr: 'الأحمر البركاني',
      primary: '#FF0000',
      secondary: '#CC0000',
      accent: '#FF6600',
      background: ['#0a0000', '#1a0000', '#0a0000'],
      surface: 'rgba(255, 0, 0, 0.1)',
      text: '#ffffff',
      textSecondary: '#FF9999',
      border: 'rgba(255, 0, 0, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FF0000',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Volcanic red theme',
    descriptionAr: 'ثيم الأحمر البركاني',
    category: 'colorful',
  },
  {
    id: 'aurora-purple',
    name: 'Aurora Purple',
    nameAr: 'البنفسجي الشفق',
    theme: {
      id: 'aurora-purple',
      name: 'Aurora Purple',
      nameAr: 'البنفسجي الشفق',
      primary: '#8B00FF',
      secondary: '#6A00CC',
      accent: '#FF00FF',
      background: ['#050005', '#150015', '#050005'],
      surface: 'rgba(139, 0, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#DD99FF',
      border: 'rgba(139, 0, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 25,
      iconStyle: 'filled',
      iconColor: '#8B00FF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Aurora purple theme',
    descriptionAr: 'ثيم البنفسجي الشفق',
    category: 'dark',
  },
  {
    id: 'titanium-gray',
    name: 'Titanium Gray',
    nameAr: 'الرمادي التيتانيوم',
    theme: {
      id: 'titanium-gray',
      name: 'Titanium Gray',
      nameAr: 'الرمادي التيتانيوم',
      primary: '#8E8E93',
      secondary: '#636366',
      accent: '#00EAFF',
      background: ['#0a0a0a', '#1a1a1a', '#0a0a0a'],
      surface: 'rgba(142, 142, 147, 0.1)',
      text: '#ffffff',
      textSecondary: '#8E8E93',
      border: 'rgba(142, 142, 147, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: false,
      blur: 20,
      iconStyle: 'outline',
      iconColor: '#8E8E93',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Titanium gray theme',
    descriptionAr: 'ثيم الرمادي التيتانيوم',
    category: 'modern',
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    nameAr: 'الشعاب المرجانية',
    theme: {
      id: 'coral-reef',
      name: 'Coral Reef',
      nameAr: 'الشعاب المرجانية',
      primary: '#FF6B6B',
      secondary: '#FF8E8E',
      accent: '#FFCC00',
      background: ['#0a0505', '#1a0a0a', '#0a0505'],
      surface: 'rgba(255, 107, 107, 0.1)',
      text: '#ffffff',
      textSecondary: '#FFCCCC',
      border: 'rgba(255, 107, 107, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FF6B6B',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Coral reef theme',
    descriptionAr: 'ثيم الشعاب المرجانية',
    category: 'colorful',
  },
  {
    id: 'lunar-white',
    name: 'Lunar White',
    nameAr: 'الأبيض القمري',
    theme: {
      id: 'lunar-white',
      name: 'Lunar White',
      nameAr: 'الأبيض القمري',
      primary: '#FFFFFF',
      secondary: '#E5E5EA',
      accent: '#00EAFF',
      background: ['#1a1a1a', '#2a2a2a', '#1a1a1a'],
      surface: 'rgba(255, 255, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#E5E5EA',
      border: 'rgba(255, 255, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 25,
      iconStyle: 'outline',
      iconColor: '#FFFFFF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Lunar white theme',
    descriptionAr: 'ثيم الأبيض القمري',
    category: 'light',
  },
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    nameAr: 'الوردي النيون',
    theme: {
      id: 'neon-pink',
      name: 'Neon Pink',
      nameAr: 'الوردي النيون',
      primary: '#FF00FF',
      secondary: '#CC00CC',
      accent: '#00FFFF',
      background: ['#050005', '#150015', '#050005'],
      surface: 'rgba(255, 0, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#FF99FF',
      border: 'rgba(255, 0, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 25,
      iconStyle: 'filled',
      iconColor: '#FF00FF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Neon pink theme',
    descriptionAr: 'ثيم الوردي النيون',
    category: 'colorful',
  },
  {
    id: 'copper-bronze',
    name: 'Copper Bronze',
    nameAr: 'البرونزي النحاسي',
    theme: {
      id: 'copper-bronze',
      name: 'Copper Bronze',
      nameAr: 'البرونزي النحاسي',
      primary: '#CD7F32',
      secondary: '#8B4513',
      accent: '#FFD700',
      background: ['#0a0500', '#1a0a00', '#0a0500'],
      surface: 'rgba(205, 127, 50, 0.1)',
      text: '#ffffff',
      textSecondary: '#FFCC99',
      border: 'rgba(205, 127, 50, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#CD7F32',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Copper bronze theme',
    descriptionAr: 'ثيم البرونزي النحاسي',
    category: 'classic',
  },
  {
    id: 'electric-yellow',
    name: 'Electric Yellow',
    nameAr: 'الأصفر الكهربائي',
    theme: {
      id: 'electric-yellow',
      name: 'Electric Yellow',
      nameAr: 'الأصفر الكهربائي',
      primary: '#FFCC00',
      secondary: '#CC9900',
      accent: '#FFFFFF',
      background: ['#0a0a00', '#1a1a00', '#0a0a00'],
      surface: 'rgba(255, 204, 0, 0.1)',
      text: '#ffffff',
      textSecondary: '#FFE599',
      border: 'rgba(255, 204, 0, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#FFCC00',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Electric yellow theme',
    descriptionAr: 'ثيم الأصفر الكهربائي',
    category: 'colorful',
  },
  {
    id: 'arctic-blue',
    name: 'Arctic Blue',
    nameAr: 'الأزرق القطبي',
    theme: {
      id: 'arctic-blue',
      name: 'Arctic Blue',
      nameAr: 'الأزرق القطبي',
      primary: '#00CCFF',
      secondary: '#0099CC',
      accent: '#FFFFFF',
      background: ['#000510', '#001020', '#000510'],
      surface: 'rgba(0, 204, 255, 0.1)',
      text: '#ffffff',
      textSecondary: '#99E5FF',
      border: 'rgba(0, 204, 255, 0.3)',
      cardStyle: 'glass',
      buttonStyle: '3d-glow',
      borderGlow: true,
      blur: 20,
      iconStyle: 'filled',
      iconColor: '#00CCFF',
      fontFamily: 'System',
      fontSize: { xs: 10, sm: 12, base: 14, md: 16, lg: 18, xl: 20, '2xl': 24, '3xl': 32 },
    },
    description: 'Arctic blue theme',
    descriptionAr: 'ثيم الأزرق القطبي',
    category: 'modern',
  },
];

export default THEMES_LIBRARY;

